name: exam1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  core:
    path: ./core
  cupertino_icons: ^1.0.2
  data:
    path: ./data
  domain: 
    path: ./domain
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localization: ^0.1.10
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^5.0.3
  fpdart: ^0.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^4.0.1
  http: ^0.13.5
  image_picker: ^0.8.6+1
  intl: ^0.17.0
  intl_utils: ^2.8.1
  json_annotation: ^4.8.0
  localizely_sdk: ^2.5.0
  meta: ^1.8.0
  path_provider: ^2.0.12
  progress_dialog_null_safe: ^1.0.7

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  dart_code_metrics: ^5.6.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  test: any
  
flutter_intl:
    enabled: true
    localizely:
      ota_enabled: true
      project_id: a92d005d-c700-4e2c-8692-f0f7afff957f

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
