name: core
description: A new Flutter module project.

version: 1.0.1+2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  fpdart: ^0.4.0

dev_dependencies:
  dart_code_metrics: ^5.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - ../assets/images/sample_image1.jpeg

  module:
    androidX: true
    androidPackage: com.example.core
    iosBundleIdentifier: com.example.core
