name: Basic Flutter Actions
on: [push]
jobs:
  basic-flutter-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      # skip this part since we still have warnings here..
      # - run: flutter analyze
      - run: flutter test