name: Basic Flutter Actions
on:   
  pull_request:
    branches:
      - main

jobs:
  basic-flutter-actions: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run analyzation
        run: flutter analyze

      - name: Run tests for presentation layer
        run: flutter test

      - name: Run tests for core layer
        run: |
          cd core
          flutter test

      - name: Run tests for data layer
        run: |
          cd data
          flutter test

      - name: Run tests for domain layer
        run: |
          cd domain
          flutter test

