name: Basic Flutter Actions
on:   
  pull_request:
    branches:
      - main

jobs:
  basic-flutter-actions: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install flutter version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run analyzation
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Install lcov
        run: |
          sudo apt-get update
          sudo apt-get install lcov

      - name: Check test coverage
        run: flutter test --coverage

      - name: generate html lcov report
        run: genhtml coverage/lcov.info -o coverage/html
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

