name: Basic Flutter Actions
on:   
  pull_request:
    types: 
      - closed

jobs:
  basic-flutter-actions:
    # will run only after pr has been merged
    if: github.event.pull_request.merged == true

    # will run in the selected os
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
      - uses: actions/checkout@v2

      - name: Installing flutter version
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Getting dependencies and analyzing code
      - run: flutter pub get
      - run: flutter analyze

      - name: Running tests
      - run: flutter test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
