name: Basic Flutter Actions
on: 
  pull_request:
    types: 
      - closed

jobs:
  basic-flutter-actions:
    # will run only after pr has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.0'
          channel: 'stable'
      - run: flutter pub get

      # skip this part since we still have warnings here..
      # - run: flutter analyze

      - run: flutter test