name: Build Version Actions
on:
  push:
    branches:
      - main

jobs:
  build-version-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'

      - name: Install flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run analization
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Install lcov
        run: |
          sudo apt-get update
          sudo apt-get install lcov

      - name: Check test coverage for presentation layer
        run: |
          flutter test --coverage
          lcov --remove coverage/lcov.info 'lib/generated/*' -o coverage/lcov.info
          genhtml coverage/lcov.info -o coverage/html

      - name: Check test coverage for domain layer
        run: |
          cd domain
          flutter test --coverage
          genhtml coverage/lcov.info -o coverage/html

      - name: Check test coverage for data layer
        run: |
          cd data
          flutter test --coverage
          lcov --remove coverage/lcov.info 'lib/src/models/*.freezed.dart' 'lib/src/models/*.g.dart' -o coverage/lcov.info
          genhtml coverage/lcov.info -o coverage/html

      - name: Check test coverage for core layer
        run: |
          cd core
          flutter test --coverage
          genhtml coverage/lcov.info -o coverage/html

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Build apk
        run: flutter build apk

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
