name: Build Version Actions
on:
  push:
    branches:
      - main

jobs:
  build-version-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'

      - name: Install flutter version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run analyzation
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Install lcov
        run: |
          sudo apt-get update
          sudo apt-get install lcov

      - name: Check test coverage
        run: flutter test --coverage

      - name: generate html lcov report
        run: genhtml coverage/lcov.info -o coverage/html

      - name: Build apk
        run: flutter build apk

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
